#!/bin/sh

# Create header
cat > "tmp/conf.c" << EOF
/* This file is generated by conf.sh, do not edit. */

#include "llenv.h"
EOF

# Declare the test suites.
for ts in $@
do
cat  >> "tmp/conf.c" << EOF
DEC_TSUITE($ts);
EOF
done

# Start the test suite list.
cat >> "tmp/conf.c" << EOF
BEGIN_TSUITES_LIST
EOF

# Add the test suites for running
for ts in $@
do
cat  >> "tmp/conf.c" << EOF
ADD_TSUITE_TO_LIST($ts)
EOF
done

# End the test suite list.
cat >> "tmp/conf.c" << EOF
END_TSUITE_LIST;
EOF
