obj-y	= smi.o
obj-y	+= sm750.o sm750_hw.o sm750_accel.o sm750_cursor.o ddk750_chip.o ddk750_power.o ddk750_mode.o
obj-y	+= ddk750_display.o ddk750_help.o ddk750_swi2c.o ddk750_sii164.o ddk750_dvi.o ddk750_hwi2c.o
obj-y	+= smi_console.o
ccflags-y += -DUSE_DVICHIP -DDVI_CTRL_SII164 -DSII164_FULL_FUNCTIONS
