#
# (C) Copyright 2018
# Baikal Electronics OJSC
# Author: Alexey Malahov <alexey.malahov@baikalelectronics.ru>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y  = board.o
obj-y += nvram.o
obj-$(CONFIG_BFK_CMD_SERVICE) += cmd_service.o oem.o
