#
# (C) Copyright 2018 T-platforms JSC
# Author: Sergey Semin <sergey.semin@t-platforms.ru>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  = board.o
obj-y += bootconf.o
obj-y += fru.o
obj-$(CONFIG_CMD_SERVICE) += cmd_service.o pvt.o
